sudo: false

language: go

env:
  - GO111MODULE=on


go:
  - 1.11.x

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - $GOPATH/bin/dep ensure

script:
  - env GOOS=linux GOARCH=arm go build
  - docker build . -t kube-entropy:"$TRAVIS_BRANCH_$TRAVIS_BUILD_NUMBER_$TRAVIS_COMMIT"

after_success:
  - |
    echo ${DOCKER_PASSWORD} | docker login --username "alexlokshin" --password-stdin
    export COMMIT_TAG="$TRAVIS_BRANCH_$TRAVIS_BUILD_NUMBER_$TRAVIS_COMMIT"
    docker tag kube-entropy:$COMMIT_TAG alexlokshin/kube-entropy:${COMMIT_TAG}
    if [ "$TRAVIS_BRANCH" == "master" ]; then 
        docker tag kube-entropy:$COMMIT_TAG alexlokshin/kube-entropy:latest
    fi
    docker push alexlokshin/kube-entropy:${COMMIT_TAG}