---
nodeChaos:
  enabled: true
  fields:
    - spec.unschedulable!=true
  labels:
  interval: 5m
podChaos:
  enabled: true
  fields:
    - metadata.namespace=default
    - metadata.namespace!=kube-system
    - metadata.namespace!=docker
  labels:
    - app=my-nginx
  interval: 30s
monitoring:
  nodePortHost: localhost
  defaultIngressUrl: https://www.avsatum.com:443/
  ingressProtocol: https
  ingressPort: 443
  serviceMonitoring:
    enabled: true
    interval: 2s
    fields:
      - metadata.namespace=default
      - metadata.namespace!=kube-system
      - metadata.namespace!=docker
    labels:
      - app=my-nginx
  ingressMonitoring:
    enabled: false
    interval: 2s
    fields:
      - metadata.namespace=default
      - metadata.namespace!=kube-system
      - metadata.namespace!=docker
    labels:
      - app=my-nginx
  
