---
nodes:
  enabled: false
  fields:
    - spec.unschedulable!=true
  labels:
  interval: 5m
pods:
  enabled: true
  fields:
  labels:
  interval: 1m
ingresses:
  protocol: https
  port: 443
  defaultHost: 192.168.88.210
  selector:
    enabled: true
    interval: 2s
    fields:
      - metadata.namespace=test
    labels:
  successHttpCodes:
    - 2xx
    - 30x
    - 403

